language: php

# Install Haxe before running the test.
before_script:
  - sudo apt-get update                                # run update before installing anything
  - sudo apt-get install python-software-properties -y # for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y      # add the ubuntu ppa that contains haxe
  - sudo apt-get update                                # pull info from ppa
  - sudo apt-get install haxe -y                       # install haxe (and neko)

# Run the test!
script:
  - haxe src/tests/travis.hxml

notifications:
  irc: "irc.oceanius.com#dev"
